### ISSUE TITLE
New features: from_package() and add_entity()

### ISSUE THREAD

**Issue by lapidus** [datastory-org/frame2package#4]
@miroli, regarding new functionality to f2p, this can provide some inspiration when it comes to the section of “ingredients”:
https://ddf-utils.readthedocs.io/en/latest/recipe.html

```
cooking:
    concepts:
        # procedures for concepts here
    entities:
        # procedures for entities here
    datapoints:
        # procedures for datapoints here
```

But at the same time I think good that f2p is lean and focused on the most common workflows we see from Pandas.

I guess what I'm primarily looking for is a way to map more quickly define the basics (what was previously in the constructor of f2p) of a dataset.

For example, let's say I already have a dataset and would like to just add one more file, pseudo:

```
f2p.from_package("path")
f2p.add_data(data=df, concepts=concepts)
f2p.to_package("path")
```

Or my simpler use case where I would like to create a dataset with some concepts and entities (no datapoints):

```

concepts = [
        {
                'concept': 'country',
                'concept_type': 'entity_domain'
        },
        {
                'concept': 'some-other-country-metadata',
                'concept_type': 'String'
       }
]

f2p()
f2p.add_concepts(concepts=concepts)
f2p.add_entity(concept="country", data=dataFrame)
f2p.to_package("path")
```
